<?= $this->extend('Backend/layout') ?>

<?= $this->section('main') ?>

<div class="dashboard-main-body">
    <div class="flex flex-wrap items-center justify-between gap-2 mb-6">
        <h6 class="font-semibold mb-0 text-dark dark:text-white text-xl">Google Authenticator Setup</h6>
    </div>

    <?php if (session()->getFlashdata('error')): ?>
        <div class="alert alert-danger bg-danger-100 dark:bg-danger-600/25 text-danger-600 dark:text-danger-400 border-danger-600 border-s-4 px-6 py-3 mb-6 flex items-center justify-between rounded-lg" role="alert">
            <div class="flex items-center gap-2">
                <iconify-icon icon="mdi:alert-circle-outline" class="text-xl"></iconify-icon>
                <?= esc(session()->getFlashdata('error')) ?>
            </div>
        </div>
    <?php endif; ?>

    <div class="card h-full border border-neutral-200 dark:border-neutral-600 rounded-lg shadow-sm bg-white dark:bg-dark-2">
        <div class="card-body p-6">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-12">
                
                <!-- Left Column: Instructions & QR -->
                <div class="flex flex-col items-center justify-center border-b md:border-b-0 md:border-r border-neutral-200 dark:border-neutral-600 pb-8 md:pb-0 md:pe-12">
                     <span class="w-16 h-16 bg-primary-100 text-primary-600 rounded-full flex items-center justify-center text-3xl mb-6">
                        <iconify-icon icon="heroicons:qr-code"></iconify-icon>
                    </span>
                    <h5 class="text-lg font-semibold mb-2 text-center text-neutral-900 dark:text-white">1. Scan QR Code</h5>
                    <p class="text-neutral-500 text-center mb-6 max-w-xs">
                        Open Google Authenticator on your phone and scan the QR code below.
                    </p>
                    
                    <div class="bg-white p-4 rounded-xl border border-neutral-200 mb-6 shadow-sm">
                        <img src="<?= $qrCodeUrl ?>" alt="QR Code" class="w-48 h-48 object-contain">
                    </div>

                    <p class="text-sm text-neutral-500 mb-2">Can't scan the code?</p>
                    <div class="flex items-center gap-2 bg-neutral-100 dark:bg-neutral-700 px-4 py-2 rounded-lg">
                        <code class="font-mono font-bold text-primary-600 dark:text-primary-400 tracking-wider"><?= $secret ?></code>
                    </div>

                    <div class="mt-6">
                        <a href="/back-end/2fa/reset" class="text-sm font-medium text-danger-600 dark:text-danger-400 hover:underline flex items-center gap-1">
                            <iconify-icon icon="solar:restart-bold"></iconify-icon> Regenerate QR Code
                        </a>
                    </div>
                </div>

                <!-- Right Column: Verification Form -->
                <div class="flex flex-col justify-center md:ps-4">
                    <div class="max-w-md w-full mx-auto">
                        <span class="w-16 h-16 bg-success-100 text-success-600 rounded-full flex items-center justify-center text-3xl mb-6">
                            <iconify-icon icon="solar:shield-check-bold"></iconify-icon>
                        </span>
                        <h5 class="text-lg font-semibold mb-2 text-neutral-900 dark:text-white">2. Verify & Activate</h5>
                        <p class="text-neutral-500 mb-8">
                            Enter the 6-digit code generated by the app to confirm setup.
                        </p>

                        <form action="/back-end/2fa/enable" method="post" data-parsley-validate>
                            <?= csrf_field() ?>
                            
                            <div class="mb-6">
                                <label class="form-label text-sm font-medium mb-2 block text-neutral-900 dark:text-white">Verification Code</label>
                                <div class="relative">
                                    <div class="absolute top-1/2 start-4 -translate-y-1/2 text-neutral-400">
                                        <iconify-icon icon="solar:lock-password-outline"></iconify-icon>
                                    </div>
                                    <input type="text" name="code" 
                                        class="form-control w-full h-[50px] ps-11 border border-neutral-300 dark:border-neutral-600 bg-neutral-50 dark:bg-neutral-800 text-neutral-900 dark:text-white rounded-lg focus:border-primary-600 focus:ring-1 focus:ring-primary-600 outline-none transition-all placeholder:text-neutral-400 text-lg tracking-widest"
                                        placeholder="000 000"
                                        required 
                                        autocomplete="off"
                                        pattern="[0-9]*" 
                                        inputmode="numeric">
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary w-full justify-center h-[50px] flex items-center gap-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg transition-colors font-medium">
                                <iconify-icon icon="solar:check-circle-bold" class="text-xl"></iconify-icon>
                                Activate 2FA
                            </button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<?= $this->endSection() ?>
